# Travis-CI.org build script

# use the new containerized infrastructure
sudo: false

#dist: trusty
dist: bionic

# language: c
# compiler:
#   - gcc
#   - clang
# env:
#   - PY=2
#   - PY=3

language: python
python:
  - "2.7"
  - "3.5"
  - "3.7"
  - "3.8"

env:
  - CC=gcc
  - CC=clang

install:
    - python --version
    - pip --version
    - pip install numpy fitsio
    - make
    - make py
    - make extra

script:
    - make test
    - (cd util; ./test)
    - (cd blind; ./test)
    - (cd libkd; ./test)
    - make install INSTALL_DIR=~/an PYTHON_SCRIPT="/usr/bin/env python"
    - ls ~/an/lib/python
    - export PATH=${PATH}:~/an/bin
    - build-astrometry-index -d 3 -o index-9918.fits -P 18 -S mag -B 0.1 -s 0 -r 1 -I 9918 -M -i demo/tycho2-mag6.fits
    - echo -e 'add_path .\ninparallel\nindex index-9918.fits' > 99.cfg
    - solve-field --config 99.cfg demo/apod4.jpg  --continue
    - tablist demo/apod4.match
    - listhead demo/apod4.wcs
    - export PYTHONPATH=${PYTHONPATH}:~/an/lib/python
    - python -c "import astrometry.libkd.spherematch"

addons:
  apt:
    packages:
    - libnetpbm10
    - libnetpbm10-dev
    - netpbm
    - wcslib-dev
    - libcfitsio-dev
    - swig
    - gsl-bin
    - libgsl-dev